var math = require('./mathlib')()
console.log(math.add(2,2))
console.log(math.multiply(5,10))
console.log(math.square(5))
console.log('random starts')
console.log(math.random(1,10))
console.log(math.random(1,10))
console.log(math.random(1,10))
console.log(math.random(1,10))
console.log(math.random(1,10))
